-- Create a table for public profiles
-- Note: We are using this as a custom auth table, decoupling from supabase auth.users
create table profiles (
  id uuid default gen_random_uuid() primary key,
  username text unique,
  email text unique not null,
  password text not null,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Set up Row Level Security (RLS) for profiles
alter table profiles enable row level security;

-- Allow public access for our custom auth flow
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Allow public registration" on profiles
  for insert with check (true);

create policy "Allow public updates" on profiles
  for update using (true);

-- Create categories table
create table categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table categories enable row level security;

create policy "Categories are viewable by everyone." on categories
  for select using (true);

-- Only Authenticated Admin can insert categories
create policy "Admin can insert categories" on categories
  for insert with check (auth.role() = 'authenticated');

-- Create blogs table
create table blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image_url text,
  author_id uuid not null, -- Removed foreign key constraint to profiles to allow admin (who might not be in profiles)
  category_id bigint references categories(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table blogs enable row level security;

create policy "Blogs are viewable by everyone." on blogs
  for select using (true);

-- Only Authenticated Admin can insert/update/delete blogs
create policy "Admin can insert blogs" on blogs
  for insert with check (auth.role() = 'authenticated');

create policy "Admin can update blogs" on blogs
  for update using (auth.role() = 'authenticated');

create policy "Admin can delete blogs" on blogs
  for delete using (auth.role() = 'authenticated');

-- Create comments table
create table comments (
  id bigint generated by default as identity primary key,
  content text not null,
  blog_id bigint references blogs(id) on delete cascade not null,
  user_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table comments enable row level security;

create policy "Comments are viewable by everyone." on comments
  for select using (true);

create policy "Allow public comment insert" on comments
  for insert with check (true);

create policy "Allow public comment delete" on comments
  for delete using (true);

-- Create likes table
create table likes (
  id bigint generated by default as identity primary key,
  blog_id bigint references blogs(id) on delete cascade not null,
  user_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(blog_id, user_id)
);

alter table likes enable row level security;

create policy "Likes are viewable by everyone." on likes
  for select using (true);

create policy "Allow public like insert" on likes
  for insert with check (true);

create policy "Allow public like delete" on likes
  for delete using (true);
